version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: ./analitica
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always  # Reiniciar en caso de fallo
    deploy:
      resources:
        limits:
          memory: 4G      # Limitar la memoria a 4 GB
          cpus: "2.0"     # Usar hasta 2 vCPUs
    networks:
      - my_network

  frontend:
    container_name: frontend
    build:
      context: ./geni
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always  # Reiniciar en caso de fallo
    deploy:
      resources:
        limits:
          memory: 2G      # Limitar la memoria a 2 GB
          cpus: "1.0"     # Usar hasta 1 vCPU
    environment:
      - API_URL=http://backend:8000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    name: geni_learninganalytics_my_network
